# Generated by Django 4.2.23 on 2025-10-05 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام موضوع خبر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'موضوع خبر',
                'verbose_name_plural': 'موضوعات خبر',
            },
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع خبر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'نوع خبر',
                'verbose_name_plural': 'انواع خبر',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'پلتفرم',
                'verbose_name_plural': 'پلتفرم\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('name_en', models.CharField(max_length=100, verbose_name='نام انگلیسی')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='نام کاربری')),
                ('user_id', models.BigIntegerField(verbose_name='آیدی کاربری')),
                ('main_group', models.CharField(max_length=100, verbose_name='گروه اصلی')),
                ('sub_group', models.CharField(blank=True, max_length=100, null=True, verbose_name='گروه فرعی')),
                ('tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='تگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'گروه کاربری',
                'verbose_name_plural': 'گروه\u200cهای کاربری',
                'indexes': [models.Index(fields=['username'], name='posts_userg_usernam_0bee7c_idx'), models.Index(fields=['user_id'], name='posts_userg_user_id_34515e_idx'), models.Index(fields=['main_group'], name='posts_userg_main_gr_ae8aea_idx'), models.Index(fields=['tag'], name='posts_userg_tag_ab9b4f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PoliticalCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='نام کاربری')),
                ('user_id', models.BigIntegerField(verbose_name='آیدی کاربری')),
                ('main_current', models.CharField(max_length=100, verbose_name='جریان اصلی')),
                ('sub_current', models.CharField(blank=True, max_length=100, null=True, verbose_name='جریان فرعی')),
                ('tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='تگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'جریان سیاسی',
                'verbose_name_plural': 'جریان\u200cهای سیاسی',
                'indexes': [models.Index(fields=['username'], name='posts_polit_usernam_9b9549_idx'), models.Index(fields=['user_id'], name='posts_polit_user_id_42c558_idx'), models.Index(fields=['main_current'], name='posts_polit_main_cu_3cdf16_idx'), models.Index(fields=['tag'], name='posts_polit_tag_114bbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='نام کاربری')),
                ('user_id', models.BigIntegerField(verbose_name='آیدی کاربری')),
                ('channel_type', models.CharField(choices=[('political', 'Political Current'), ('user_group', 'User Group')], max_length=20, verbose_name='نوع کانال')),
                ('main_category', models.CharField(max_length=100, verbose_name='دسته\u200cبندی اصلی')),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='دسته\u200cبندی فرعی')),
                ('tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='تگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.platform', verbose_name='پلتفرم')),
            ],
            options={
                'verbose_name': 'کانال',
                'verbose_name_plural': 'کانال\u200cها',
            },
        ),
        migrations.CreateModel(
            name='UserProvinceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.province', verbose_name='استان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسترسی کاربر به استان',
                'verbose_name_plural': 'دسترسی کاربران به استان\u200cها',
                'unique_together': {('user', 'province')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='لینک پست')),
                ('lang_post', models.CharField(max_length=10, verbose_name='زبان پست')),
                ('like_count', models.IntegerField(default=0, verbose_name='تعداد لایک')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('carousel', 'Carousel'), ('text', 'Text')], max_length=10, verbose_name='نوع مدیا')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('comment_count', models.IntegerField(default=0, verbose_name='تعداد کامنت')),
                ('username', models.CharField(max_length=100, verbose_name='نام کاربری')),
                ('extracted_hashtag', models.TextField(blank=True, null=True, verbose_name='هشتگ\u200cهای استخراج شده')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10, verbose_name='احساس')),
                ('npo', models.BooleanField(default=False, verbose_name='NPO')),
                ('emo', models.BooleanField(default=False, verbose_name='EMO')),
                ('tag', models.TextField(blank=True, null=True, verbose_name='تگ')),
                ('extracted_mention', models.TextField(blank=True, null=True, verbose_name='منشن\u200cهای استخراج شده')),
                ('reply_text', models.TextField(blank=True, null=True, verbose_name='متن پاسخ')),
                ('reply_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کاربری پاسخ دهنده')),
                ('datetime_create', models.DateTimeField(verbose_name='تاریخ ایجاد')),
                ('datetime_robot', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ربات')),
                ('id_source', models.CharField(max_length=100, verbose_name='آیدی منبع')),
                ('view_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('copy_count', models.IntegerField(default=0, verbose_name='تعداد کپی')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.channel', verbose_name='کانال')),
                ('news_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.newstopic', verbose_name='موضوع خبر')),
                ('news_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.newstype', verbose_name='نوع خبر')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.platform', verbose_name='پلتفرم')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست\u200cها',
                'indexes': [models.Index(fields=['username'], name='posts_post_usernam_633e69_idx'), models.Index(fields=['datetime_create'], name='posts_post_datetim_16d70f_idx'), models.Index(fields=['province'], name='posts_post_provinc_afbefe_idx'), models.Index(fields=['platform'], name='posts_post_platfor_72ffc6_idx'), models.Index(fields=['channel'], name='posts_post_channel_1c9b1b_idx'), models.Index(fields=['news_type'], name='posts_post_news_ty_bf2bcc_idx'), models.Index(fields=['news_topic'], name='posts_post_news_to_241a9a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['username'], name='posts_chann_usernam_cd4c14_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['user_id'], name='posts_chann_user_id_903828_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['channel_type'], name='posts_chann_channel_b49ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['main_category'], name='posts_chann_main_ca_f83616_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['platform'], name='posts_chann_platfor_d65637_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['tag'], name='posts_chann_tag_c7a004_idx'),
        ),
    ]
