# Generated by Django 4.2.23 on 2025-10-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_politicalcategory_usercategory_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='channel',
            name='posts_chann_main_ca_f83616_idx',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='main_category',
        ),
        migrations.AddField(
            model_name='channel',
            name='name_fa',
            field=models.CharField(default='', max_length=100, verbose_name='نام فارسی کانال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='political_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='posts.politicalcategory', verbose_name='دسته\u200cبندی سیاسی'),
        ),
        migrations.AddField(
            model_name='channel',
            name='user_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='posts.usercategory', verbose_name='دسته کاربری اصلی'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('political', 'جریان سیاسی'), ('user_group', 'گروه کاربری')], max_length=20, verbose_name='نوع کانال'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['political_category'], name='posts_chann_politic_f4814c_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['user_category'], name='posts_chann_user_ca_3ace49_idx'),
        ),
    ]
