# Generated by Django 4.2.23 on 2025-10-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_channel_posts_chann_main_ca_f83616_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id_source',
        ),
    ]
