# Generated by Django 4.2.23 on 2025-10-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_id_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='code',
            field=models.CharField(default='', max_length=100, verbose_name='کد'),
            preserve_default=False,
        ),
    ]
