# Generated by Django 4.2.23 on 2025-10-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_province_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('political', 'جریان سیاسی'), ('user_group', 'گروه کاربری'), ('no_type', 'فاقد نوع')], max_length=20, verbose_name='نوع کانال'),
        ),
    ]
