# Generated by Django 4.2.23 on 2025-10-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_channel_channel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('text', 'Text'), ('document', 'Document')], max_length=10, verbose_name='نوع مدیا'),
        ),
    ]
