# Generated by Django 4.2.23 on 2025-10-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='province_query',
            field=models.TextField(blank=True, null=True, verbose_name='کوئری استان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('notok', 'NotOK')], max_length=10, verbose_name='احساس'),
        ),
    ]
