# Generated by Django 4.2.23 on 2025-10-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_province_province_query_alter_post_sentiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newstopic',
            old_name='description',
            new_name='news_topic_query',
        ),
        migrations.RenameField(
            model_name='newstype',
            old_name='description',
            new_name='news_type_query',
        ),
    ]
