# Generated by Django 4.2.23 on 2025-10-28 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_description_newstopic_news_topic_query_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام برنامه')),
                ('tv_program_query', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'موضوع خبر',
                'verbose_name_plural': 'موضوعات خبر',
            },
        ),
    ]
