# Generated by Django 4.2.23 on 2025-10-28 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_tvprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tv_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.tvprogram', verbose_name='نام برنامه'),
        ),
    ]
