# Generated by Django 4.2.23 on 2025-10-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_tv_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tvprogram',
            options={'verbose_name': 'نام برنامه', 'verbose_name_plural': 'نام برنامه ها'},
        ),
    ]
