# Generated by Django 4.2.23 on 2025-10-28 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_tvprogram_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام اصلی')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='سمت')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='دسته')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='celebrities/', verbose_name='عکس')),
                ('original_id', models.CharField(max_length=100, unique=True, verbose_name='آیدی')),
                ('member_count', models.IntegerField(default=0, verbose_name='تعداد اعضا')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('join_date', models.DateTimeField(verbose_name='تاریخ پیوستن')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.platform', verbose_name='پلتفرم')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'چهره',
                'verbose_name_plural': 'چهره\u200cها',
                'indexes': [models.Index(fields=['name'], name='posts_celeb_name_961c09_idx'), models.Index(fields=['category'], name='posts_celeb_categor_21887a_idx'), models.Index(fields=['platform'], name='posts_celeb_platfor_050418_idx'), models.Index(fields=['province'], name='posts_celeb_provinc_fed0c7_idx'), models.Index(fields=['original_id'], name='posts_celeb_origina_4534b5_idx')],
            },
        ),
    ]
