# Generated by Django 4.2.23 on 2025-10-28 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_celebrity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebrityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='لینک پست')),
                ('lang_post', models.CharField(max_length=10, verbose_name='زبان پست')),
                ('like_count', models.IntegerField(default=0, verbose_name='تعداد لایک')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('text', 'Text'), ('document', 'Document')], max_length=10, verbose_name='نوع مدیا')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('comment_count', models.IntegerField(default=0, verbose_name='تعداد کامنت')),
                ('extracted_hashtag', models.TextField(blank=True, null=True, verbose_name='هشتگ\u200cهای استخراج شده')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('notok', 'NotOK')], max_length=10, verbose_name='احساس')),
                ('npo', models.BooleanField(default=False, verbose_name='NPO')),
                ('emo', models.BooleanField(default=False, verbose_name='EMO')),
                ('tag', models.TextField(blank=True, null=True, verbose_name='تگ')),
                ('extracted_mention', models.TextField(blank=True, null=True, verbose_name='منشن\u200cهای استخراج شده')),
                ('reply_text', models.TextField(blank=True, null=True, verbose_name='متن پاسخ')),
                ('reply_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کاربری پاسخ دهنده')),
                ('datetime_create', models.DateTimeField(verbose_name='تاریخ ایجاد')),
                ('datetime_robot', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ربات')),
                ('view_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('copy_count', models.IntegerField(default=0, verbose_name='تعداد کپی')),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.celebrity', verbose_name='نام چهره')),
                ('news_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.newstopic', verbose_name='موضوع خبر')),
                ('news_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.newstype', verbose_name='نوع خبر')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.platform', verbose_name='پلتفرم')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'پست چهره',
                'verbose_name_plural': 'پست\u200cهای چهره',
                'indexes': [models.Index(fields=['datetime_create'], name='posts_celeb_datetim_52b780_idx'), models.Index(fields=['province'], name='posts_celeb_provinc_090b7c_idx'), models.Index(fields=['platform'], name='posts_celeb_platfor_10233d_idx'), models.Index(fields=['news_type'], name='posts_celeb_news_ty_e685d9_idx'), models.Index(fields=['news_topic'], name='posts_celeb_news_to_789fd9_idx'), models.Index(fields=['celebrity'], name='posts_celeb_celebri_b526ee_idx'), models.Index(fields=['sentiment'], name='posts_celeb_sentime_1a1373_idx')],
            },
        ),
    ]
