# Generated by Django 4.2.23 on 2025-10-28 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_celebritypost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام اصلی')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='سمت')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='دسته')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='عکس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل\u200cها',
                'indexes': [models.Index(fields=['name'], name='posts_profi_name_507185_idx'), models.Index(fields=['category'], name='posts_profi_categor_d7c871_idx'), models.Index(fields=['position'], name='posts_profi_positio_b5819d_idx'), models.Index(fields=['province'], name='posts_profi_provinc_98b044_idx')],
            },
        ),
    ]
