# Generated by Django 4.2.23 on 2025-10-28 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_profile'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='celebrity',
            name='posts_celeb_name_961c09_idx',
        ),
        migrations.RemoveIndex(
            model_name='celebrity',
            name='posts_celeb_categor_21887a_idx',
        ),
        migrations.RemoveIndex(
            model_name='celebrity',
            name='posts_celeb_provinc_fed0c7_idx',
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='category',
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='position',
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='province',
        ),
        migrations.AddField(
            model_name='celebrity',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='celebrities', to='posts.profile', verbose_name='پروفایل'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='celebrity',
            index=models.Index(fields=['profile'], name='posts_celeb_profile_fd81d1_idx'),
        ),
    ]
