# Generated by Django 4.2.23 on 2025-10-28 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_remove_celebrity_posts_celeb_name_961c09_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='celebrity',
            name='posts_celeb_profile_fd81d1_idx',
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='profile',
        ),
        migrations.AddField(
            model_name='celebrity',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='دسته'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='نام اصلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celebrity',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='celebrities/', verbose_name='عکس'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سمت'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='province',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.province', verbose_name='استان'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='celebrity',
            index=models.Index(fields=['name'], name='posts_celeb_name_961c09_idx'),
        ),
        migrations.AddIndex(
            model_name='celebrity',
            index=models.Index(fields=['category'], name='posts_celeb_categor_21887a_idx'),
        ),
        migrations.AddIndex(
            model_name='celebrity',
            index=models.Index(fields=['province'], name='posts_celeb_provinc_fed0c7_idx'),
        ),
    ]
