# Generated by Django 4.2.23 on 2025-11-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_remove_celebrity_posts_celeb_name_961c09_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='api/profiles/', verbose_name='عکس'),
        ),
    ]
