# Generated by Django 4.2.23 on 2025-11-09 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefineChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام فارسی کانال')),
                ('username', models.CharField(max_length=100, verbose_name='نام کاربری')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.platform', verbose_name='پلتفرم')),
                ('political_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='definechannels', to='posts.politicalcategory', verbose_name='دسته\u200cبندی سیاسی')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.province', verbose_name='استان')),
                ('user_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='definechannels', to='posts.usercategory', verbose_name='دسته کاربری اصلی')),
            ],
            options={
                'verbose_name': 'کانال',
                'verbose_name_plural': 'کانال\u200cها',
                'indexes': [models.Index(fields=['username'], name='posts_defin_usernam_69dbb7_idx'), models.Index(fields=['political_category'], name='posts_defin_politic_d18660_idx'), models.Index(fields=['user_category'], name='posts_defin_user_ca_5ceb4d_idx'), models.Index(fields=['platform'], name='posts_defin_platfor_29f685_idx')],
            },
        ),
    ]
