# Generated by Django 4.2.23 on 2025-11-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_definechannel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definechannel',
            options={'verbose_name': 'تعریف کانال', 'verbose_name_plural': 'تعریف کانال\u200cها'},
        ),
        migrations.CreateModel(
            name='DefineTvProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام برنامه')),
                ('tv_program_query', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'تعریف برنامه',
                'verbose_name_plural': 'تعریف برنامه ها',
            },
        ),
    ]
