# Generated by Django 4.2.23 on 2025-11-09 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_definechannel_options_definetvprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefineProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام اصلی')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='سمت')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='دسته')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='api/define-profiles/', verbose_name='عکس')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'تعریف چهره',
                'verbose_name_plural': 'تعریف چهره',
                'indexes': [models.Index(fields=['name'], name='posts_defin_name_a26ad2_idx'), models.Index(fields=['category'], name='posts_defin_categor_29941d_idx'), models.Index(fields=['position'], name='posts_defin_positio_6eb13d_idx'), models.Index(fields=['province'], name='posts_defin_provinc_b58f03_idx')],
            },
        ),
    ]
