# Generated by Django 4.2.23 on 2025-11-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='defineprofile',
            name='name_fa',
            field=models.CharField(default='', max_length=100, verbose_name='نام فارسی کانال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defineprofile',
            name='username',
            field=models.CharField(default='', max_length=100, verbose_name='نام کاربری'),
            preserve_default=False,
        ),
    ]
