# Generated by Django 4.2.23 on 2025-11-15 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_defineprofile_name_fa_defineprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='defineprofile',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.platform', verbose_name='پلتفرم'),
            preserve_default=False,
        ),
    ]
