# Generated by Django 4.2.23 on 2025-11-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_defineprofile_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='member',
            field=models.IntegerField(default=0, verbose_name='تعداد عضو'),
            preserve_default=False,
        ),
    ]
